// Code generated by "stringer -type=tool"; DO NOT EDIT.

package cross_platform

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[brush-0]
	_ = x[spawner-1]
	_ = x[eraser-2]
	_ = x[heater-3]
	_ = x[cooler-4]
}

const _tool_name = "brushspawnereraserheatercooler"

var _tool_index = [...]uint8{0, 5, 12, 18, 24, 30}

func (i tool) String() string {
	if i < 0 || i >= tool(len(_tool_index)-1) {
		return "tool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tool_name[_tool_index[i]:_tool_index[i+1]]
}
