// Code generated by "stringer -type=Tool"; DO NOT EDIT.

package extra

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Brush-0]
	_ = x[Spawner-1]
	_ = x[Eraser-2]
	_ = x[Heater-3]
	_ = x[Cooler-4]
}

const _Tool_name = "BrushSpawnerEraserHeaterCooler"

var _Tool_index = [...]uint8{0, 5, 12, 18, 24, 30}

func (i Tool) String() string {
	if i < 0 || i >= Tool(len(_Tool_index)-1) {
		return "Tool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tool_name[_Tool_index[i]:_Tool_index[i+1]]
}
