// Code generated by "stringer -type=Mat"; DO NOT EDIT.

package mat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Sand-1]
	_ = x[Glass-2]
	_ = x[Water-3]
	_ = x[Iron-4]
	_ = x[Oxygen-5]
	_ = x[Hydrogen-6]
	_ = x[CarbonDioxide-7]
	_ = x[Methane-8]
	_ = x[Coal-9]
	_ = x[IronOxide-10]
	_ = x[Aluminum-11]
	_ = x[AluminumOxide-12]
	_ = x[IronThermite-13]
	_ = x[Magnesium-14]
	_ = x[MagnesiumOxide-15]
	_ = x[Sulfur-16]
	_ = x[SulfurTrioxide-17]
	_ = x[BlackPowder-18]
	_ = x[SulfuricAcid-19]
	_ = x[Kaolinite-20]
	_ = x[Metakaolin-21]
	_ = x[CalciumCarbonate-22]
	_ = x[CalciumOxide-23]
}

const _Mat_name = "NoneSandGlassWaterIronOxygenHydrogenCarbonDioxideMethaneCoalIronOxideAluminumAluminumOxideIronThermiteMagnesiumMagnesiumOxideSulfurSulfurTrioxideBlackPowderSulfuricAcidKaoliniteMetakaolinCalciumCarbonateCalciumOxide"

var _Mat_index = [...]uint8{0, 4, 8, 13, 18, 22, 28, 36, 49, 56, 60, 69, 77, 90, 102, 111, 125, 131, 145, 156, 168, 177, 187, 203, 215}

func (i Mat) String() string {
	if i < 0 || i >= Mat(len(_Mat_index)-1) {
		return "Mat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mat_name[_Mat_index[i]:_Mat_index[i+1]]
}
