// Code generated by "stringer -type=Mat"; DO NOT EDIT.

package mat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Sand-1]
	_ = x[Water-2]
	_ = x[Iron-3]
	_ = x[Oxygen-4]
	_ = x[Hydrogen-5]
}

const _Mat_name = "NoneSandWaterIronOxygenHydrogen"

var _Mat_index = [...]uint8{0, 4, 8, 13, 17, 23, 31}

func (i Mat) String() string {
	if i < 0 || i >= Mat(len(_Mat_index)-1) {
		return "Mat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mat_name[_Mat_index[i]:_Mat_index[i+1]]
}
